.PHONY: all clean

all:
	make -C c++/
	make -C bloom_filter/
	make -C comb/
	make -C console/
	make -C rng/

clean:
	make -C c++/ clean
	make -C bloom_filter/ clean
	make -C comb/ clean
	make -C console/ clean
	make -C rng/ clean
